### ISSUE TITLE
Newsletter/beta request confirmation email 

### ISSUE THREAD

**Issue by verysanghee** [ungleich/dynamicweb#299]
**Problem**
The dcl logo in newsletter subscription email redirects to ungleich home (https://datacenterlight.ungleich.ch/) instead of dcl site

**Goal**
The dcl logo should redirect to dcl 
<img width="652" alt="screen shot 2017-06-02 at 11 44 58" src="https://cloud.githubusercontent.com/assets/10186611/26727165/fac92e50-47a5-11e7-8be0-881fdd8062c1.png">

**Comment by Modulos** [comment]
@verysanghee thanks for this issue! You can use the Assignees on the right side to choose who you want to assign this issue as well as set the correct label for your issue - bug I guess in this case -.

**Comment by verysanghee** [comment]
Thanks for the tips! I'll assign all the email issues to you, maybe this way it's easier. You can be responsible for all mail issues.

**Comment by pcoder** [comment]
I think this may not be a bug really, and I think it works as expected. 
Here is my observation:
- If I subscribe to the newsletter on https://datacenterlight.ch, I receive an email with the logo pointing to https://datacenterlight.ch
- If I subscribe to the newsletter on https://dynamicweb-staging.ungleich.ch/datacenterlight, I receive an email with the logo pointing to https://dynamicweb-staging.ungleich.ch

The code behind this is https://github.com/ungleich/dynamicweb/blob/master/datacenterlight/templates/datacenterlight/emails/request_access_confirmation.html#L78
which seems to correctly use the `{{base_url}}` for the logo. 

During my tests to reproduce the bug, I never found the link of logo pointing to a url other than the host that generated the email.

**Comment by pcoder** [comment]
This issue is outdated. So, closing this.
